services:
  library_bd:
    image: postgres:16.0
    ports:
      - '{POSTGRES_DB_PORT}:${POSTGRES_DB_DOCKER_PORT}'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: library_bd
    volumes:
      - library_bd_data:/var/lib/postgresql/data
    restart: always

volumes:
  library_bd_data: